#include <stm32f4xx.h>
int main(void)
{
  SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);
  SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
  SET_BIT(RCC->APB2ENR, RCC_APB2ENR_SYSCFGEN);

  MODIFY_REG(SYSCFG->EXTICR[3], 0xF << 4, SYSCFG_EXTICR4_EXTI13_PC); // bind PC13 to EXTI13
  CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_SYSCFGEN); //SYSCFG not needed after configuring

  MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODE5_1, GPIO_MODER_MODE5_0); // PA5 output (LD2)
  CLEAR_BIT(GPIOC->MODER, (GPIO_MODER_MODE13_0 | GPIO_MODER_MODE13_1)); // PC13 input (USER B1)

  SET_BIT(EXTI->IMR, EXTI_IMR_IM13);
  SET_BIT(EXTI->RTSR, EXTI_RTSR_TR13);
  CLEAR_BIT(EXTI->FTSR, EXTI_FTSR_TR13);

  NVIC_EnableIRQ(EXTI15_10_IRQn); 

  while (1)
  {
  }
}

void EXTI15_10_IRQHandler(void) 
{
  if (READ_BIT(EXTI->PR, 1 << 13))
  {
    if (READ_BIT(GPIOA->IDR, GPIO_IDR_ID5))
      GPIOA->BSRR = GPIO_BSRR_BR5;
    else
      GPIOA->BSRR = GPIO_BSRR_BS5;
  };
  SET_BIT(EXTI->PR, 1 << 13);
}
